name:                sinsemilla
version:             0.1.0.0
github:              "githubuser/sinsemilla"
license:             MIT
author:              "Alfredo Garcia"
maintainer:          "example@example.com"
copyright:           "2023 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            sinsemilla hash function implementation
# category:            Crypto

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/oxarbitrage/sinsemilla#readme>

dependencies:
- base >= 4.7 && < 5
- pasta-curves
- bytestring
- utf8-string
- split

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  sinsemilla-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sinsemilla
    - bytestring
    - utf8-string
    - split

tests:
  sinsemilla-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sinsemilla
    - bytestring
    - utf8-string
    - split
